include: package:lint/analysis_options.yaml

linter:
  rules:
    # ------ Disable individual rules ----- #
    #                 ---                   #
    # Turn off what you don't like.         #
    # ------------------------------------- #

    # Use parameter order as in json response
    constant_identifier_names: false
    avoid_function_literals_in_foreach_calls: false

    # Util classes are awesome!
    avoid_classes_with_only_static_members: false

    # Blindly follow the Flutter code style, which prefers types everywhere
    always_specify_types: true

    prefer_double_quotes: true
